version: 0.2

# env:
#   # This will set the value of $AWS_ACCESS_KEY_ID to the value of the ACCESS_KEY environment variable in CodeBuild
#   AWS_ACCESS_KEY_ID: $ACCESS_KEY


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 286414711246.dkr.ecr.ap-south-1.amazonaws.com/loco
      - REPOSITORY_URI=286414711246.dkr.ecr.ap-south-1.amazonaws.com/loco
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=python-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
#       - sudo systemctl status docker
#       - sudo systemctl start docker
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
    
      - export AWS_ACCESS_KEY_ID=$ACCESS_KEY 
      - echo $AWS_ACCESS_KEY_ID 
#       - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY 
#       - echo $AWS_SECRET_ACCESS_KEY 
#       - aws sts get-caller-identity  
#       - aws eks update-kubeconfig --region ap-south-1 --name demo2 
#       - cat ~/.kube/config 
      
      
#       - cat deployment.yml 
#       - kubectl get node 
#       - kubectl apply -f deployment.yml 
      
    
