version: 0.2

# env:
#   # This will set the value of $AWS_ACCESS_KEY_ID to the value of the ACCESS_KEY environment variable in CodeBuild
#   AWS_ACCESS_KEY_ID: $ACCESS_KEY


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 286414711246.dkr.ecr.ap-south-1.amazonaws.com/loco
      - REPOSITORY_URI=286414711246.dkr.ecr.ap-south-1.amazonaws.com/loco
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=python-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      
      - echo "Update AWS CLI"
      - pip3 uninstall -y awscli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - export PATH=$PATH:/usr/local/bin
      - echo "Install Kubectl"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - kubectl version --client
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
#       - sudo systemctl status docker
#       - sudo systemctl start docker
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
#       - aws eks update-kubeconfig --name demo2
      - echo Build completed on `date`
      - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - aws eks update-kubeconfig --name demo2
      - export AWS_ACCESS_KEY_ID=AKIAUFL5FVHHBL3AEAVW
      - echo $AWS_ACCESS_KEY_ID
    
#       - export AWS_ACCESS_KEY_ID=$ACCESS_KEY 
#       - echo $AWS_ACCESS_KEY_ID 
#       - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY 
#       - echo $AWS_SECRET_ACCESS_KEY 
#       - aws sts get-caller-identity  
#       - aws eks update-kubeconfig --name demo2 
#       - cat ~/.kube/config 
      
      
#       - cat deployment.yml 
#       - kubectl get node 
#       - kubectl apply -f deployment.yml 
      
    
